.TH jubaclient 1 2018-02-04

.SH NAME

jubaclient \- Jubatus CLI client (unofficial)

.SH SYNOPSIS

.B jubaclient
.I service
.I method
[
.B "-p"
.I port
]
[
.B "-h"
.I hostname
]
[
.B "-n"
.I name
]
[
.B "-t"
.I timeoutSeconds
]

.B jubaclient
.B -i
[
.I service
]
[
.I method
]
[
.B "-p"
.I port
]
[
.B "-h"
.I hostname
]
[
.B "-n"
.I name
]
[
.B "-t"
.I timeoutSeconds
]

.SH DESCRIPTION

.PP
The 
.B jubaclient
command requests JSON received from standard input with the specified method to the Jubatus server, and returns the response to the standard output.

.TP
.SH Interactive mode
With
the
.B "-i"
option,
it will be in interactive mode. When choosing service and method, it provides keyword completion system. When you send Ctrl-C (SIGINT) you return to choosing the service and method, and sending Ctrl-D (EOT) will end the process.

.SH OPTIONS

.TP
.I service

service name (classifier, nearest_neighbor, etc.)

.TP
.I method


service method (get_status, train, get_k_center, etc.)

.TP
.B "-i, --interactive"

interactive mode

.TP
.B "-p <port>, --port=<port>"

server port number (default 9199)

.TP
.B "-h <hostname>, --host=<hostname>"

server hostname (default localhost)

.TP
.B "-n <name>, --name=<name>"

name of target cluster (default '')

.TP
.B "-t <timeoutSeconds>, --timeout=<timeoutSeconds>"

request timeout  (default 0)

.SH BUGS

.TP
Presumably. Report them or discuss them at:

https://github.com/naokikimura/jubaclient/issues

.SH EXAMPLE

.TP
#save(id):

echo '[ "jubaclient_save_1" ]' | jubaclient classifier save 

.TP
#get_config():

echo '[]' | jubaclient classifier get_config | jq '.|fromjson' 

.TP
classifier#classify(data):

jubaclient classifier classify <<EOF | jq '.'

[ [ [ [ [ "message", "<b>quuz</b>" ] ] ] ] ]

EOF

.SH AUTHORS

Naoki Kimura <n.kimura.cap@gmail.com>

.SH SEE ALSO

JUBATUS_SERVER(8), jq(1)